[package]
name = "gen-serdec"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.11"
clap = { version = "3.2.20", features = ["derive"] }
